name: Publish Docker image

on:
  push:
    tags:
      - 'v*'        # dispara quando você criar uma tag tipo v2.3.1
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag
        id: meta
        run: |
          # TAG refere-se ao nome da tag sem o "refs/tags/"
          ref="${GITHUB_REF##*/}"
          echo "tag=${ref}" >> $GITHUB_OUTPUT

      - name: Build and Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/evolution-api:${{ steps.meta.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/evolution-api:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/evolution-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/evolution-api:buildcache,mode=max
